apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:1
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /volume-dentro-do-container
      name: primeiro-volume
  - name: jenkins-container
    image: jenkins/jenkins:alpine
    ports:
    - containerPort: 8082
    volumeMounts:
    - mountPath: /volume-dentro-do-container
      name: primeiro-volume
  volumes:
  - name: primeiro-volume
    hostPath:
      path: /data/primeiro-volume/  
