spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api_test
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    docker:
      compose:
        skip:
          in-tests: false