USE loja_virtual;

CREATE TABLE PRODUTO (
  ID BIGINT AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  DESCRICAO VARCHAR(255) NULL,
  PRIMARY KEY (ID)) Engine = InnoDB;
  
INSERT INTO PRODUTO(NOME, DESCRICAO) VALUES ('Notebook Dell', 'G3');
INSERT INTO PRODUTO(NOME, DESCRICAO) VALUES ('Smart TV', '43');
INSERT INTO PRODUTO(NOME, DESCRICAO) VALUES ('Geladeira', 'Duplex 430l');
INSERT INTO PRODUTO(NOME, DESCRICAO) VALUES ('Mesa Jantar', '6 lugares');

CREATE TABLE CATEGORIA (
    ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL ,

    PRIMARY KEY (ID)
) Engine = InnoDB;

INSERT INTO CATEGORIA(NOME) VALUES ('ELETRÔNICOS');
INSERT INTO CATEGORIA(NOME) VALUES ('ELETRODOMESTICOS');
INSERT INTO CATEGORIA(NOME) VALUES ('MOVEIS');
SELECT * FROM CATEGORIA;

SELECT * FROM CATEGORIA;

ALTER TABLE PRODUTO ADD COLUMN CATEGORIA_ID BIGINT;

ALTER TABLE PRODUTO ADD FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID);
UPDATE PRODUTO SET CATEGORIA_ID = 1 WHERE id = 1;
UPDATE PRODUTO SET CATEGORIA_ID = 1 WHERE id = 2;
UPDATE PRODUTO SET CATEGORIA_ID = 2 WHERE id = 3;
UPDATE PRODUTO SET CATEGORIA_ID = 3 WHERE id = 4;